Update Loading effect
XRFoundation/Universal-Volumetric pull request #89
Opened 2022-03-12 21:49 UTC by rondoor124

- update logic for the loading effect
- adding event handler
- restructure
- fix some unexpected issue.
[issue remained]
- the html video player is crashed on the low performance 
- doesn't work smoothly on the low internet traffic environment

2022-03-12 22:13 UTC, speigg requested changes

2022-03-12 22:13 UTC, speigg commented on web/player.ts
> +    this._video.setAttribute('playsInline', 'playsInline');
playsinline attribute should be all lowercase, and the value should be an empty string

2022-03-12 22:13 UTC, speigg commented on web/player.ts
> +    this._video.setAttribute('muted', 'muted');
value should be empty string

2022-03-14 06:30 UTC, speigg commented
When I test this branch w/ the [Volumetric Player](https://github.com/XRFoundation/UniversalVolumetric-Demo) the videoStatus stays on VideoStatusEnum.Set. 

My steps:

In Universal-Volumetric repo (this branch):
```
npm run build
npm link
```

In Volumetric Player repo:
```
npm i
npm link volumetric
npm run dev
```

Then I try the sample volumetric videos, and they don't play. Does the player need to be updated?

2022-03-14 09:36 UTC, rondoor124 commented
Thanks for the review!
I did not try to check with Volumetric Player, I will check soon.

2022-03-14 17:56 UTC, merged